// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0msFM8gLNzB3KOqVl6HjxEsj7rIRlbxo',
    appId: '1:1033882721805:ios:4e7a2cac1145de3b65bf44',
    messagingSenderId: '1033882721805',
    projectId: 'quickbite-fcrit-927fc',
    databaseURL: 'https://quickbite-fcrit-927fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickbite-fcrit-927fc.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0msFM8gLNzB3KOqVl6HjxEsj7rIRlbxo',
    appId: '1:1033882721805:ios:4e7a2cac1145de3b65bf44',
    messagingSenderId: '1033882721805',
    projectId: 'quickbite-fcrit-927fc',
    databaseURL: 'https://quickbite-fcrit-927fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickbite-fcrit-927fc.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw8FDqmg1ftjL_iwYb6Pth0GfsylgrL6w',
    appId: '1:1033882721805:web:44e73011cf50939665bf44',
    messagingSenderId: '1033882721805',
    projectId: 'quickbite-fcrit-927fc',
    authDomain: 'quickbite-fcrit-927fc.firebaseapp.com',
    databaseURL: 'https://quickbite-fcrit-927fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickbite-fcrit-927fc.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw8FDqmg1ftjL_iwYb6Pth0GfsylgrL6w',
    appId: '1:1033882721805:web:44e73011cf50939665bf44',
    messagingSenderId: '1033882721805',
    projectId: 'quickbite-fcrit-927fc',
    authDomain: 'quickbite-fcrit-927fc.firebaseapp.com',
    databaseURL: 'https://quickbite-fcrit-927fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickbite-fcrit-927fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvzS-440fsvpN_xG4BNZ2a3tZeX2s1_4',
    appId: '1:1033882721805:android:e85c24dcf74d822165bf44',
    messagingSenderId: '1033882721805',
    projectId: 'quickbite-fcrit-927fc',
    databaseURL: 'https://quickbite-fcrit-927fc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickbite-fcrit-927fc.firebasestorage.app',
  );

}